name: CI devops 2022 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: master 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-20.04
    steps:
     #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify -f simple-api/pom.xml
